### ISSUE TITLE
Error tooltip is not a function

### ISSUE THREAD

**Issue by seisvalt** [drsdre/yii2-wizardwidget#11]
When run the sample code,  launches  error  
wizardwidget.js:3 Uncaught TypeError: $(...).tooltip is not a function

Line 3

$('.nav-tabs > li a[title]').**tooltip**();

**Comment by drsdre** [comment]
That sounds like the Bootstrap js or underlying Jquery js is not being loaded. This should have been fixed some time ago. Can you check if you have loaded the latest release?
