### ISSUE TITLE
Css class

### ISSUE THREAD

**Issue by Denis4yk** [drsdre/yii2-wizardwidget#12]
Great work, but I have to "stole" and add ability to set css class of the container. Would be glad to saw that feature in future releases.

**Comment by drsdre** [comment]
If you can create a push request on your fork with your changes, I can check to see how to integrate your changes back into the main branch.

Andre

**Comment by Denis4yk** [comment]
@drsdre I'm just not quite good at coding and gitHub. Better not to do it for now) Thank you for your answer.
