### ISSUE TITLE
Splitting big form

### ISSUE THREAD

**Issue by felipe-carrasco** [drsdre/yii2-wizardwidget#14]
Hi drsdre,
I have a form that is a little bit extensive (all fields go into one model), so I splitted it into four parts with one _stepN.php file each, and put the widget in the main _form.php.
All works (validations, widgets, etc.) except the saving part. When I click the submit button nothing is saved into DB, all fields except from step1 are cleared, no on screen errror.
And if I look into the Yii2 Dev Tool there're stored only the variables from the first step.
What could be wrong?

**Comment by drsdre** [comment]
Hi Felipe,

If you can post the code for the wizard setup, I can try to help debug this.

**Comment by felipe-carrasco** [comment]
Thanks drsdre, here are the involved parts:
1. This is the wizard setup:
`<?php
global $form;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OrdenDeCompra */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="orden-de-compra-form">

    <?php $form = ActiveForm::begin(['options' => ['role' => 'form']]); ?>

    <?php $form->errorSummary($model); ?>

    <?= $form->field($model, 'estado_id')->hiddenInput(['value' => 1])->label(false) ?>

    <?= $form->field($model, 'usuario_id')->hiddenInput(['value' => Yii::$app->user->identity->id])->label(false) ?>

    <?php
        $wizard_config = [
            'id' => 'stepwizard',
            'steps' => [
                1 => [
                    'title' => 'Paso 1: Datos Empresa',
                    'icon' => 'glyphicon glyphicon-home',
                    'buttons' => [
                        'next' => [
                            'title' => 'Siguiente',
                            'options' => ['class' => 'btn btn-primary']
                         ],
                     ],
                     'content' => $this->render('_step1', ['form' => $form, 'model' => $model]),
                ],
                2 => [
                    'title' => 'Paso 2: Datos Proveedor',
                    'icon' => 'glyphicon glyphicon-user',
                    //'skippable' => false,
                    'buttons' => [
                        'next' => [
                            'title' => 'Siguiente',
                            'options' => ['class' => 'btn btn-primary']
                        ],
                        'prev' => [
                            'title' => 'Anterior'
                        ],
                    ],
                    'content' => $this->render('_step2', ['form' => $form, 'model' => $model]),
                ],
                3 => [
                    'title' => 'Paso 3: Pago y Transporte',
                    'icon' => 'glyphicon glyphicon-usd',
                    'buttons' => [
                        'next' => [
                            'title' => 'Siguiente',
                            'options' => ['class' => 'btn btn-primary']
                        ],
                        'prev' => [
                            'title' => 'Anterior'
                        ],
                    ],
                    'content' => $this->render('_step3', ['form' => $form, 'model' => $model]),
                ],
                4 => [
                    'title' => 'Paso 4: Información Adicional',
                    'icon' => 'glyphicon glyphicon-info-sign',
                    'buttons' => [
                        'prev' => [
                            'title' => 'Anterior'
                        ],
                        'save' => [
                            'html' => Html::submitButton('Guardar',
                            [
                                'class' => 'btn btn-success',
                                'id' => 'wizard-step4-final',
                                //'name' => 'step',
                                'value' => 'save-final'
                            ]),
                            'title' => 'Guardar'
                        ],
                    ],
                    'content' => $this->render('_step4', ['form' => $form, 'model' => $model]),
                ],
            ],
            'start_step' => 1,
            // Optional final screen
            //'complete_content' => "Listo!, Ahora agregue productos a su Orden de Compra."
        ];
        ?>

    <?= \drsdre\wizardwidget\WizardWidget::widget($wizard_config); ?>

    <?php ActiveForm::end(); ?>

</div>`
2. As stated above, each step is a different file, an ActiveForm with different widgets each (dropdownlist, date picker, etc). Thanks in advance for your time and help.

**Comment by drsdre** [comment]
I don't see any issues in your code. I would recommend to have a look at the produced HTML code of the form and check if all the field names are created like 'OrdenDeCompra[fieldname]'. You can post the code here if you want.

**Comment by felipe-carrasco** [comment]
Ok, I solved it, the problem was that I was using ActiveForm widgets on each of the stepN.php files. Somehow I overlooked that in one of the closed issues here. So, just put ActiveForm in your main form (where the wizard widget is setup).
