### ISSUE TITLE
Next Button as ajax verify/submit button

### ISSUE THREAD

**Issue by JackFK** [drsdre/yii2-wizardwidget#17]
Hi,
I have serveral steps, each with its own form. Everyting is working with a dedicated submit button, but how could i combine the next-button with the submit?
Best would be to:
* verify
* submit
* go to the next step

How could i achieve that?

Thanks for your help!

greetings, Florian

ps.: thanks for implementing that!

**Comment by drsdre** [comment]
You have two options here:
1. You remove the next button and only leave the submit button. When you push the form data to the server, you have the client return back to the page with the wizard and set the parameter 'start_step' in the wizard setup to the next step.
2. You connect submit to the next button with Javascript and have the form data send with ajax to the server. When the form data is validated and returns true, the next step is displayed.

Keep in mind that in particular with option 1 when the users goes back a step, any unsaved data from the forms on the other steps will be lost.
