### ISSUE TITLE
Set content in view by HTML instead of a string?

### ISSUE THREAD

**Issue by tstkenny** [drsdre/yii2-wizardwidget#2]
Hi!  This is exactly I have been struggling for days!  Keep it up!

I am still working on how to set the content of each step by the HTML content to this widget, instead of assigning a bunch of html tags into a string.  Any chance you can provide an example please?  

My ultimate goal is to integrate this widget into DynamicForm Widget for 1-to-many data entry.

Thank you!

**Comment by drsdre** [comment]
An option for easier management of the steps is to work with separate view files for each step. In the example below you will have to create _step1.php, _step2.php, _step3.php and _step4.php files in the directory where the wizard is being setup in a view file.

``` php
$form = ActiveForm::begin(['options' => ['role' => 'form']]);
$wizard_config = [
    'steps' => [
        '1' => [
            'title' => 'Step 1',
            'icon' => 'glyphicon glyphicon-cloud-download',
            'content' => $this->render('_step1', ['form' => $form, 'dataset' => $dataset]),
            'buttons' => [
                'next' => [
                    'title' => 'Next: Step2',
                    'options' => ['disabled' => is_null($data_service_id)?true:false, 'class'=> 'btn btn-success']
                ]
            ],
        ],
        '2' => [
            'title' => 'Step 2',
            'icon' => 'glyphicon glyphicon-cloud-upload',
            'content' => $this->render('_step2', ['form' => $form, 'dataset' => $dataset]),
            'buttons' => [
                'next' => [
                    'title' => 'Next: Filter&Map data',
                    'options' => ['disabled' => 'true', 'class'=> 'btn btn-success', 'type'=> 'submit']
                ]
            ],
        ],
        '3' => [
            'title' => 'Step 3',
            'icon' => 'glyphicon glyphicon-filter',
            'content' => $this->render('_step3', ['form' => $form, 'dataset' => $dataset]),
        ],
        '4' => [
            'title' => 'Step 4',
            'icon' => 'glyphicon glyphicon-transfer',
            'content' => $this->render('_step4', ['form' => $form, 'dataset' => $dataset]),
        ],
    ],
    'complete_content' => "You are done!",
    'start_step' => $step,
];

echo \drsdre\wizardwidget\WizardWidget::widget($wizard_config);

ActiveForm::end();
```

**Comment by tstkenny** [comment]
Thank you so much drsdre!  This is a great idea.  If _step1,2,3,4 only have plain HTML tags they should work.  

When I tried to include some ActiveForm elemets in _step1.php, it requires to include an ActiveForm::begin which makes it a nested ActiveForm inside the master View's ActiveForm.  Should I put plain HTML form in _step1 instead?

I inspect the main View source and $wizard_config are being put before JQuery.  I think it can be fixed by RequireJS thingy.  I will figure it out later.

I almost forced to drop Yii2 since my project must have a working guided form with dynamic add/remove child elements.  I even tried to integrate Jquery steps to Yii2 and Yii 1.x wizard.behavior but they are far beyond my knowledge.

Thanks again drsdre!  You are leading me the right direction!

**Comment by drsdre** [comment]
Regarding ActiveForm, in the example you can see that I initiate a general ActiveFrom definition in the $form parameter. This parameter is send to each step view and can be used directly within.

For dynamic add/remove elements also check:
Pjax in-page updates, see http://blog.neattutorials.com/yii2-pjax-tutorial/
Dependent Dropdown, see http://demos.krajee.com/widgets#depdrop

Good luck.
