### ISSUE TITLE
glyphicon icon not in center

### ISSUE THREAD

**Issue by syaifulrmdhn** [drsdre/yii2-wizardwidget#21]
Sorry, I'm using adminlte template, How about this? could you show me the fault of this? please
![wizard image](https://user-images.githubusercontent.com/24586705/32759805-ecb67a76-c91d-11e7-91f7-4d3a16c271cd.PNG)
sources such as bootstrap, jquery, etc. are complete.

**Comment by drsdre** [comment]
Possibly some upper CSS is messing up the centering. Please check the CSS tree for the icons in Firebug or Chrome Developer tools. If you need help with this, please provide a temporary environment with the UI which I can access.

Andre

**Comment by drsdre** [comment]
Closing this as no more information was provided.
