### ISSUE TITLE
how to validate on each step of the wizard

### ISSUE THREAD

**Issue by gredek** [drsdre/yii2-wizardwidget#23]
I would like to validate the fields displayed on each step of the wizard, so when the user clicks the 'next' button, a validation happens (following the rules in the model), when validation is passed the wizard goes to the next step.

As I see the recommendation from the previous questions asked concerning this subject in these issues topic the best way to do this is by creating a form with submit button for each step and displaying the fields I want from the model into this form. I am working with 1 model divided into different steps in the wizard. But what would be the best implementation to use this kind of setup. Do I need to create a from with submit button in each view file, or do I still need the use the next and html code for the wizard setup? For the submitting I think I need to catch this in the controller and then render the view to the next step if validation passes. 

I am kind of stuck with the implementation for a form on each step with a submit button on the bottom right side of the form/step. Because when I implement the submit button in the view (step), a default next button is displayed and the submit button in the view is not styled easily like the next/prev buttons.

**Comment by drsdre** [comment]
Two options:
1. You create a form for each step that sends the data to the backend and model for validation. Either to store the form data in a session variable or (if possible) create a new record and keep adding/changing data at each step.
2. You split one form across multiple steps and only on last step you send the data to the server. (Frontend) validation for the steps you have to create yourself in Javascript most likely or trigger specific rules when clicking next (and stop next step till all validation is true).

**Comment by dpchami** [comment]
How can I bind the on click function with next step button so that to send the form data to server
