### ISSUE TITLE
disable step

### ISSUE THREAD

**Issue by Dasheel** [drsdre/yii2-wizardwidget#27]
Hi drsdre is there a way to make a second of what my variable is worth seeing or not one more step? Could we make sure to change the color of the icons and resize them? Thanks

**Comment by drsdre** [comment]
Hi Dasheel. I'm not sure if I understand what you are trying to accomplish. Can you provide me an example of a flow you want to make?

**Comment by Dasheel** [comment]
I apologize, I explained myself wrong. When I render a view, I return a variable to it. Based on what value this variable has, the widget should show me 2 or 3 steps. It's possible?
If the variable is equal to 1 I should have three steps, if the variable is equal to w I should have only two steps.
Sorry for my bad english
```
<?php
$moreStep="";
if($var==1){
	$moreStep= 3 => [
			'title' => 'Step 3',
			'icon' => 'glyphicon glyphicon-transfer',
			'content' => '<h3>Step 3</h3>This is step 3',
		];
}
$wizard_config = [
	'id' => 'stepwizard',
	'steps' => [
		1 => [
			'title' => 'Step 1',
			'icon' => 'glyphicon glyphicon-cloud-download',
			'content' => '<h3>Step 1</h3>This is step 1',
			'buttons' => [
				'next' => [
					'title' => 'Forward', 
					'options' => [
						'class' => 'disabled'
					],
				 ],
			 ],
		],
		2 => [
			'title' => 'Step 2',
			'icon' => 'glyphicon glyphicon-cloud-upload',
			'content' => '<h3>Step 2</h3>This is step 2',
			'skippable' => true,
		],
		$morestep,
	],
	'complete_content' => "You are done!", // Optional final screen
	'start_step' => 1, // Optional, start with a specific step
];
?>

<?= \drsdre\wizardwidget\WizardWidget::widget($wizard_config); ?>
```

**Comment by drsdre** [comment]
Try this:

```
<?php
$wizard_config = [
	'id' => 'stepwizard',
	'steps' => [
		1 => [
			'title' => 'Step 1',
			'icon' => 'glyphicon glyphicon-cloud-download',
			'content' => '<h3>Step 1</h3>This is step 1',
			'buttons' => [
				'next' => [
					'title' => 'Forward', 
					'options' => [
						'class' => 'disabled'
					],
				 ],
			 ],
		],
		2 => [
			'title' => 'Step 2',
			'icon' => 'glyphicon glyphicon-cloud-upload',
			'content' => '<h3>Step 2</h3>This is step 2',
			'skippable' => true,
		],
	],
	'complete_content' => "You are done!", // Optional final screen
	'start_step' => 1, // Optional, start with a specific step
];
if($var==1){
	$wizard_config['steps'][3] = [
			'title' => 'Step 3',
			'icon' => 'glyphicon glyphicon-transfer',
			'content' => '<h3>Step 3</h3>This is step 3',
		];
}
?>

<?= \drsdre\wizardwidget\WizardWidget::widget($wizard_config); ?>
```

**Comment by Dasheel** [comment]
Thanks a lot. It works perfectly.
I have another question: in one step I render a page which has a form (ActiveForm) and a model. In this page I am going to insert the data of the address, as for example at home. Is there a way to put a button that "duplicates" the view I render, under the fields already rendered in order to add another address?

**Comment by Dasheel** [comment]
Thanks a lot. It works perfectly.
I have another question: in one step I render a page which has a form (ActiveForm) and a model. In this page I am going to insert the address data. Is there a way to put a button that "duplicates" the view I render, under the fields already rendered in order to add another address? Like in a example
![Cattura2](https://user-images.githubusercontent.com/32876274/78150229-4b165700-7437-11ea-8a84-707d1a23e811.PNG)
![Cattura](https://user-images.githubusercontent.com/32876274/78150233-4baeed80-7437-11ea-9f59-e761d2fe0170.PNG)

**Comment by Dasheel** [comment]
Thanks a lot. It works perfectly.
