### ISSUE TITLE
fix in views line and options

### ISSUE THREAD

**Issue by Lawiet** [drsdre/yii2-wizardwidget#4]
[WizardWidget.txt](https://github.com/drsdre/yii2-wizardwidget/files/257630/WizardWidget.txt)

good friend, I have seen a few mistakes like I might correct and kept a record of what I have done to help your component is very full for wizard, the changes I've made are just to help improve your component are as follows:

line 59
`
// count optimize
$count = count($this->steps)+($this->complete_content?1:0);

// Wizard content
$wizard_line = '';
$wizard_line_distribution = round(100 / ($count + ($count/100)) ); // count fix when is pair
$wizard_line_width = round(100-(100/$count)); // fix width to line is minor to 3 or mayor to 7
$tab_content = '';
`

and 
`
$wizard_line .= '<li role="presentation" class="'.$class.'" style="width:'.$wizard_line_distribution.'%" '.$html_options.'>'. ......
`

and last 

`
$wizard_line .= '<li role="presentation" class="'.$class.'" style="width:'.$wizard_line_distribution.'%">'.
`

thanks.

Note: sorry my bad english

**Comment by drsdre** [comment]
Hi Lawiet,

Would you be able to fork of this repository and create a pull request with the fixes applied?

Andre

**Comment by Lawiet** [comment]
Ok, done.

https://github.com/Lawiet/yii2-wizardwidget

**Comment by drsdre** [comment]
Thank you. Can you trigger a 'pull request' too? (should be in the top menu of your fork code overview)

Andre

**Comment by drsdre** [comment]
Hi Lawiet,

I've integrated your fix for wizard linewidth and handling of options for the tabs. However the implementation has been changed to use the Yii2 BaseHtml library.

Regarding the Javascript enhancements for 'data-function', can you explain to me how that would work different from adding normal javascript onclick functionality to the buttons?

Drsdre
