### ISSUE TITLE
Unable to change the properties of 'previous' button

### ISSUE THREAD

**Issue by arvidthd** [drsdre/yii2-wizardwidget#9]
```
....
                2 => [
                    'title' => 'Step 2',
                    'icon' => 'glyphicon glyphicon-cloud-upload',
                    'content' => Yii::$app->controller->renderPartial('_permohonan_usulan_kegiatan.php'),
                    'buttons' => [
                        'next' => [
                            'title' => 'Go Next>', 
                            'options' => [
                                'class' => 'btn btn-primary'
                            ],
                         ],
                         'previous' => [
                            'title' => 'Go Back >', 
                            'options' => [
                                'class' => 'btn btn-primary'
                            ],
                         ],
                     ],
                ],
.....
```

I added the "previous" properties to change the 'previous' button, but nothing happen. The 'previous' button still using the same class and the title (button text) didn't change to 'Go Back'.
Am i using the wrong properties or wrong place to put it?

**Comment by drsdre** [comment]
Hi Arvidthd,

You found a discrepancy between the documentation and implementation. The implementation uses the key 'prev' instead of 'previous'. To be backwards compatible, I will update the documentation accordingly.

**Comment by arvidthd** [comment]
Thank you, sorry clearly i didn't read / try the docs carefully. Keep awesome @drsdre i love your plugins.
